global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'warehouse-service'
    static_configs:
      - targets: ['warehouse-service:8080']
        labels:
          service: 'warehouse'
          environment: 'docker'

  - job_name: 'central-monitoring-service'
    static_configs:
      - targets: ['central-monitoring-service:8081']
        labels:
          service: 'monitoring'
          environment: 'docker'
